name: Run Postman Tests

on:
  push:
    branches: [ main ]

jobs:
  postman-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman and HTML Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Create reports directory
        run: mkdir reports

      - name: Run Postman Tests
        run: |
          newman run Restfull_Booker.postman_collection.json `
            --environment Book_Environment.postman_environment.json `
            --reporters cli,html `
            --reporter-html-export reports/report.html

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: postman-report
          path: reports/
